version: "3.1"

services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis
    restart: always
    hostname: redis
    container_name: redis
    environment:
      REDIS_PASSWORD: "admin"
    ports:
      - '6379:6379'

  rabbitmq:
    image: 'rabbitmq:3.8-management'
    restart: always
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "qrcode"
      RABBITMQ_DEFAULT_PASS: "qrcode"
    ports:
      - "5672:5672"
      - "15672:15672"